import { BaseGame } from '../core/game.js';

/**
 * LIGHTS OUT
 *
 * Press a light and it toggles, along with its four neighbours. Turn them all
 * off. That is the entire rule set, and it takes about four seconds to learn
 * and considerably longer to be good at.
 *
 * Puzzles are generated by starting from a solved board and pressing random
 * cells, which guarantees solvability — the operation is its own inverse, so
 * pressing the same set again undoes it. It also hands us a par: pressing a
 * cell twice cancels out, so the number of *distinct* cells pressed is a
 * solution, and beating it means you found a shorter one.
 */

const SIZES = { 5: { grid: 5, presses: 6 }, 6: { grid: 6, presses: 9 } };

const W = 520;
const H = 560;
const BOARD_TOP = 76;

export default class LightsOut extends BaseGame {
  static id = 'lightsout';
  static width = W;
  static height = H;
  static renderer = '2d';
  static touch = 'point';
  static smooth = true;
  static hudPad = { top: 34, bottom: 24 };
  static hudLabels = { score: 'Score', secondary: 'Puzzle' };

  static options = [
    {
      id: 'size',
      label: 'Grid',
      default: '5',
      choices: [
        { value: '5', label: '5×5', hint: 'The classic board.' },
        { value: '6', label: '6×6', hint: 'A bigger board, and a good deal harder.' },
      ],
    },
  ];

  setup() {
    this.host.setSecondaryLabel('Puzzle');
    this.host.setHint('Click a light — it toggles with its neighbours',
      'Tap a light — it toggles with its neighbours');
    this.setLives(3);

    this.puzzleNo = 1;
    this.breakTimer = 0;
    this.#build(this.option('size'));
    this.banner('Turn them off');
    this.play('ready');
  }

  onOptionChange(id, value) {
    if (id !== 'size') return false;
    this.#build(value);
    return true;
  }

  #build(sizeKey) {
    const def = SIZES[sizeKey] ?? SIZES[5];
    this.n = def.grid;
    this.sizeKey = sizeKey;

    // Scale the board to the canvas rather than fixing the cell size.
    const span = Math.min(W - 80, H - BOARD_TOP - 90);
    this.cell = Math.floor(span / this.n);
    this.boardW = this.cell * this.n;
    this.boardX = (W - this.boardW) / 2;
    this.boardY = BOARD_TOP;

    this.lights = Array(this.n * this.n).fill(false);

    // Press random cells from a solved board. Solvable by construction.
    const pressed = new Set();
    const count = def.presses + Math.min(6, Math.floor(this.puzzleNo / 2));
    for (let i = 0; i < count; i++) {
      const index = Math.floor(this.random() * this.n * this.n);
      this.#press(index, true);
      // Pressing the same cell twice is a no-op, so track the distinct set.
      if (pressed.has(index)) pressed.delete(index);
      else pressed.add(index);
    }

    // A board that generated itself into the solved state is no puzzle.
    if (this.lights.every((v) => !v)) {
      this.#press(Math.floor(this.random() * this.n * this.n), true);
      this.par = 1;
    } else {
      this.par = pressed.size;
    }

    this.moves = 0;
    this.elapsed = 0;
    this.solved = false;
    this.host.setSecondary(this.puzzleNo);
    this.meta = { puzzle: this.puzzleNo, grid: `${this.n}x${this.n}` };
  }

  /** Toggle a cell and its orthogonal neighbours. */
  #press(index, silent = false) {
    const n = this.n;
    const row = (index / n) | 0;
    const col = index % n;
    const targets = [[row, col], [row - 1, col], [row + 1, col], [row, col - 1], [row, col + 1]];

    for (const [r, c] of targets) {
      if (r < 0 || r >= n || c < 0 || c >= n) continue;
      const i = r * n + c;
      this.lights[i] = !this.lights[i];
      if (!silent) {
        this.flash ??= new Map();
        this.flash.set(i, 0);
      }
    }
  }

  #remaining() {
    return this.lights.reduce((n, on) => n + (on ? 1 : 0), 0);
  }

  #solve() {
    this.solved = true;
    const underPar = Math.max(0, this.par - this.moves);
    const bonus = 600 + underPar * 300 + Math.max(0, 120 - Math.round(this.elapsed) * 2) * 4;
    this.addScore(bonus);
    this.banner(this.moves <= this.par ? 'Par or better!' : 'Lights out');
    this.play('highscore');
    this.puzzleNo++;
    this.breakTimer = 1.6;
  }

  /* =============================================================== update */

  update(dt) {
    this.updateEffects(dt);
    if (this.over) return;

    if (this.flash) {
      for (const [i, t] of this.flash) {
        if (t > 0.3) this.flash.delete(i);
        else this.flash.set(i, t + dt);
      }
    }

    if (this.breakTimer > 0) {
      this.breakTimer -= dt;
      if (this.breakTimer <= 0) this.#build(this.sizeKey);
      return;
    }

    this.elapsed += dt;

    // Wandering too far past par costs a life — otherwise you could flail at
    // it forever and the score would mean nothing.
    if (this.moves > this.par + 14) {
      const lives = this.lives - 1;
      this.setLives(Math.max(0, lives));
      this.play('die');
      this.shake.add(8);
      if (lives <= 0) {
        this.end();
        return;
      }
      this.banner('Reset');
      this.#build(this.sizeKey);
      return;
    }

    const m = this.mouse;
    if (!m.pressed) return;
    const col = Math.floor((m.x - this.boardX) / this.cell);
    const row = Math.floor((m.y - this.boardY) / this.cell);
    if (col < 0 || col >= this.n || row < 0 || row >= this.n) return;

    this.#press(row * this.n + col);
    this.moves++;
    this.play('toggle');
    this.tone(280 + this.#remaining() * 18, { dur: 0.07, gain: 0.1, type: 'square' });

    if (!this.#remaining()) this.#solve();
  }

  /* ================================================================= draw */

  draw(ctx) {
    this.clear(ctx, '#06080f');
    ctx.save();
    this.shake.apply(ctx);

    this.#drawHeader(ctx);

    for (let i = 0; i < this.n * this.n; i++) {
      const x = this.boardX + (i % this.n) * this.cell;
      const y = this.boardY + ((i / this.n) | 0) * this.cell;
      const on = this.lights[i];
      const pad = 5;
      const flash = this.flash?.get(i);

      ctx.save();
      if (on) {
        const pulse = flash != null ? 1 - flash / 0.3 : 0;
        ctx.fillStyle = '#fbbf24';
        ctx.shadowColor = '#fbbf24';
        ctx.shadowBlur = 18 + pulse * 22;
      } else {
        ctx.fillStyle = '#161d2b';
      }
      this.roundRect(ctx, x + pad, y + pad, this.cell - pad * 2, this.cell - pad * 2, 10).fill();
      ctx.restore();

      if (!on) {
        ctx.save();
        ctx.strokeStyle = 'rgba(255,255,255,0.06)';
        ctx.lineWidth = 1;
        this.roundRect(ctx, x + pad, y + pad, this.cell - pad * 2, this.cell - pad * 2, 10).stroke();
        ctx.restore();
      } else {
        // A darker core, so a lit cell reads as a bulb rather than a blob.
        ctx.save();
        ctx.globalAlpha = 0.22;
        ctx.fillStyle = '#7c4a03';
        this.roundRect(ctx, x + this.cell * 0.3, y + this.cell * 0.3, this.cell * 0.4, this.cell * 0.4, 6).fill();
        ctx.restore();
      }
    }

    this.drawEffects(ctx);
    ctx.restore();
  }

  #drawHeader(ctx) {
    const left = this.#remaining();
    this.text(ctx, `${left} LIT`, W / 2, 32, {
      size: 18, color: left ? '#fbbf24' : '#4ade80', glow: 10,
    });

    const overPar = this.moves - this.par;
    const label =
      this.moves === 0 ? `par ${this.par}`
      : overPar <= 0 ? `${this.moves} moves · ${-overPar} under par`
      : `${this.moves} moves · ${overPar} over par`;
    this.text(ctx, label.toUpperCase(), W / 2, 56, {
      size: 10, color: overPar > 0 ? '#8b93a7' : '#4ade80',
    });
  }
}
